# Generated by Django 2.0.6 on 2018-06-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('un', '未处理'), ('applying', '申请中'), ('verified', '已审核')], default='un', max_length=8, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'holdlot',
                'verbose_name_plural': 'holdlots',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=3, verbose_name='机种')),
                ('num', models.CharField(max_length=8, verbose_name='批次号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('kind', 'num')},
        ),
        migrations.AddField(
            model_name='holdlot',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold_lot', to='tft.Lot'),
        ),
        migrations.AddField(
            model_name='holdlot',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
