# Generated by Django 2.0.6 on 2018-07-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveraudit',
            name='recover_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='tft.RecoverOrder', verbose_name='复机申请单'),
        ),
    ]
