# Generated by Django 2.0.6 on 2018-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复机签复时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_sign_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生产签停时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生产签复时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qc_sign_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='品质签复时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='related_sign_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='责任工程签停时间'),
        ),
    ]
