# Generated by Django 2.0.6 on 2018-07-11 14:39

from django.db import migrations, models
import tft.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=tft.models.order.default_order_sn, max_length=20, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
