# Generated by Django 2.0.6 on 2018-07-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_auto_20180704_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveraudit',
            name='qc_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_recoveraudits', to=settings.AUTH_USER_MODEL, verbose_name='QC签停'),
        ),
        migrations.AlterField(
            model_name='recoveraudit',
            name='qc_time',
            field=models.DateTimeField(verbose_name='QC签停时间'),
        ),
        migrations.AlterField(
            model_name='recoveraudit',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='拒签理由'),
        ),
        migrations.AlterField(
            model_name='recoveraudit',
            name='remark',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='生产批注'),
        ),
        migrations.AlterField(
            model_name='recoverorder',
            name='explain',
            field=models.TextField(blank=True, max_length=300, verbose_name='先行lot结果说明'),
        ),
        migrations.AlterField(
            model_name='recoverorder',
            name='solution',
            field=models.TextField(blank=True, max_length=300, verbose_name='责任单位对策说明'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startaudit',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='拒签理由'),
        ),
    ]
