# Generated by Django 2.0.6 on 2018-07-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_auto_20180701_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='草稿箱'),
        ),
    ]
