# Generated by Django 2.0.6 on 2018-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_auto_20180711_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
