# Generated by Django 2.0.6 on 2018-07-09 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0005_auto_20180705_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startorder',
            name='charge_users',
            field=models.ManyToManyField(blank=True, related_name='charged_startorders', to=settings.AUTH_USER_MODEL, verbose_name='通知制程人员'),
        ),
        migrations.AlterField(
            model_name='startorder',
            name='lot_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='受害批次数'),
        ),
        migrations.AlterField(
            model_name='startorder',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='noticed_startorders', to=settings.AUTH_USER_MODEL, verbose_name='通知生产人员'),
        ),
    ]
