# Generated by Django 2.0.6 on 2018-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/%Y/%m', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='真名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
