# Generated by Django 2.0.6 on 2018-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180627_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/%Y/%m', verbose_name='头像'),
        ),
    ]
