# Generated by Django 2.0.6 on 2018-07-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created'], 'verbose_name': '工作流', 'verbose_name_plural': '工作流'},
        ),
    ]
