# Generated by Django 2.0.6 on 2018-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20180719_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
